#!/bin/sh
set -x

wmake libso newFreeSurface

wmake libso newFreeSurface/functionObjects/bubbleHistory

wmake libso newFreeSurface/functionObjects/dropletHistory

wmake libso newFreeSurface/functionObjects/sloshingHistory

wmake libso newFreeSurface/functionObjects/liquidBridgeHistory

wmake decomposeParSurfaceTracking

wmake newBubbleInterTrackFoam

wmake newInterTrackFoam

wmake ./utilities/setFluidIndicator

wmake ./utilities/adjustBubbleInterface
