#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

rm -rf foamTools/lnInclude 2>/dev/null
rm -rf regionModel/lnInclude 2>/dev/null
wclean regionModel || exit 1

wclean finiteArea.new || exit 1
