#!/bin/bash

# TODO [High] Sort this mess in foamUserTools.sh and put it in user/fct_tools.sh with prefix tools
# TODO [High] Sort this mess in cleanFunctions.sh and put it in case/.
# TODO [High] Sort this mess in helpFunctions.sh and put it in case/.

###############################################################################
PSD="$(dirname "${BASH_SOURCE[0]}")";
sourcePSD () { local psd="$PSD"; source "$1"; PSD="$psd"; }
###############################################################################

sourcePSD "$PSD/bashrc.d/source.sh"

###############################################################################

foamEtc=${FOAM_ETC:-"$1"}

error_fatalIfEmptyVar 'foamEtc' "bashrc"

env_set 'FOAM_ETC' "$foamEtc"
env_set 'FOAM_USER_ETC' "$PSD"

###############################################################################

feClear ()
{
    env_unsetRegex WM_.*
    env_unsetRegex FOAM_.*

    env_removeAll 'foam-extend'
}

feLoad ()
{
    # Load project environment
    source "$FOAM_ETC/bashrc" &> /dev/null

    # Load user environment
    source "$FOAM_USER_ETC/user/source.sh"
    source "$FOAM_USER_ETC/foamUserTools.sh"
}

fe ()
{
    foam_inst_dir="$FOAM_INST_DIR"
    foam_etc="$FOAM_ETC"
    foam_user_etc="$FOAM_USER_ETC"

    if path_exists "$foam_etc"; then

        # Clear environment
        feClear

        # Reset key directories
        env_set 'FOAM_ETC' "$foam_etc"
        env_set 'FOAM_USER_ETC' "$foam_user_etc"

        [ ! -z "$foam_inst_dir" ] && \
            env_set 'FOAM_INST_DIR' "$foam_inst_dir"

        # Load environment
        feLoad

    else

        local msg
            msg="Could not find 'bashrc' of foam-extend in folder"
            msg="$msg '$foam_etc'. Did you either pass the path to the"
            msg="$msg foam-extend etc-directory as parameter \$1 to"
            msg="$msg this 'bashrc' or set FOAM_ETC directly instead?"
            msg="$msg Is foam-extend really installed, correctly?"

        error_fatal "$msg" 'fe31'

    fi

}

###############################################################################

fe31

###############################################################################
