#!/bin/bash#!/bin/bash

###############################################################################
DIR="$(dirname "${BASH_SOURCE[0]}")"
###############################################################################

source "$DIR/bashrc.d/source.sh"

###############################################################################
DIR="$(dirname "${BASH_SOURCE[0]}")"
###############################################################################

# Check if basic tools are installed
dep_listIsHashedVerb 'find grep awk sed python mayavi2'

###############################################################################

env_set 'WM_PROJECT' 'foam'
env_set 'WM_FORK' 'extend'
env_set 'WM_PROJECT_VERSION' '3.1'
env_set 'WM_PROJECT_BASEDIR' "$WM_PROJECT-$WM_FORK-$WM_PROJECT_VERSION"

[ -z "$FOAM_INST_DIR" ] && env_set 'FOAM_INST_DIR' "$HOME/foam"

env_set 'FOAM_ETC' "$FOAM_INST_DIR/$WM_PROJECT_BASEDIR/etc"

###############################################################################

feClear ()
{
    env_removeAll 'foam-extend'

    env_unsetRegex WM_.*
    env_unsetRegex FOAM_.*

    while [ $# -gt 0 ]; do
        echo $1
        env_unsetRegex $1
        shift
    done
}

feUser ()
{
    source "$DIR/foamUserAliases.sh" || return $?
    source "$DIR/foamUserTools.sh" || return $?
}

fe31 ()
{
    bashrc="$FOAM_ETC/bashrc"

    if path_exists "$bashrc"; then

        # Clear foam environment
        feClear

        # Load foam-extend environment
        source "$bashrc" &> /dev/null

        # Make sure compile option is set accordingly
        env_set 'WM_COMPILE_OPTION' 'Opt'

        # Force solver to stop if NaNs exist
        env_set 'FOAM_SIGFPE' '1'

        feUser

    else

        local msg
            msg="Could not find 'bashrc' of '$WM_PROJECT_BASEDIR'" \
            msg="$msg in folder '$FOAM_ETC'." \
            msg="$msgIs '$WM_PROJECT_BASEDIR' installed, correctly?"

        # Clear foam environment
        feClear

        error_warning "$msg" 'fe31' || return 1

    fi

}

###############################################################################

fe31

###############################################################################
