#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application from controlDict
application=$(grep 'application' system/controlDict | sed 's/^\s*application\s*//g' | sed 's/;$//g');

# Cleanup
cleanCase
cleanFaMesh

# Fix bug in foam cleanFaMesh (using bash syntax with #!/bin/sh)
rm -rf constant/faMesh/faBoundary* 2>/dev/null
rm -rf constant/faMesh/faceLabels* 2>/dev/null

# Remove polyMesh boundary description
rm -rf constant/polyMesh/boundary 2>/dev/null

# Remove polyMesh and faMesh
rm -rf 'constant/polyMesh' > /dev/null 2>&1
mkdir 'constant/polyMesh' > /dev/null 2>&1
rm -rf 'constant/faMesh' > /dev/null 2>&1
mkdir 'constant/faMesh' > /dev/null 2>&1

# Remove initial time folder
rm -rf 0

if [[ $1 != 'clean' ]]; then

    # Recreate initial time folder
    mkdir 0 || exit 1

    # Restore polymesh from org backup
    cp -r 'constant/polyMesh.org/'* 'constant/polyMesh' > /dev/null 2>&1

    # Restore faMesh from org backup
    cp -r 'constant/faMesh.org/'* 'constant/faMesh' > /dev/null 2>&1

    # CheckMesh
    runApplication checkMesh || exit 1

    # Create faMesh
    runApplication makeFaMesh || exit 1

    # Copy all data from 0.org to initial time folder
    cp -r 0.org/* 0 || exit 1

    # Start solver
    runApplication $application

fi