#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application from controlDict
application=$(grep 'application' system/controlDict | sed 's/^\s*application\s*//g' | sed 's/;$//g');

# Run
runApplication blockMesh
runApplication $application
