#!/bin/bash
# August 2015
# Pascal Beckstein (p.beckstein@hzdr.de)

# TODO [High] Sort this mess in cleanFunctions.sh and put it in case/.
# TODO [High] Sort this mess in helpFunctions.sh and put it in case/.

# --------------------------------------------------------------------------- #
# --- Sourcing -------------------------------------------------------------- #
# --------------------------------------------------------------------------- #

PSD="$(dirname "${BASH_SOURCE[0]}")";
sourcePSD () { local psd="$PSD"; source "$1"; PSD="$psd"; }

# --------------------------------------------------------------------------- #

sourcePSD "$PSD/bashrc.d/source.sh"

# --------------------------------------------------------------------------- #
# --- Function definitions -------------------------------------------------- #
# --------------------------------------------------------------------------- #

feClear ()
{
    # Backup keys
    local fe32_foam_inst_dir="$FE32_FOAM_INST_DIR"
    local fe32_foam_etc="$FE32_FOAM_ETC"
    local fe32_foam_user_etc="$FE32_FOAM_USER_ETC"

    env_unsetRegex WM_.*
    env_unsetRegex FOAM_.*

    env_removeAll 'foam-extend'

    # Restore keys
    env_set 'FE32_FOAM_INST_DIR' "$fe32_foam_inst_dir"
    env_set 'FE32_FOAM_ETC' "$fe32_foam_etc"
    env_set 'FE32_FOAM_USER_ETC' "$fe32_foam_user_etc"
}


feLoad ()
{
    # Load project environment
    source "$FOAM_ETC/bashrc" &> /dev/null

    # Load user environment
    source "$FOAM_USER_ETC/user/source.sh"
}


fe32 ()
{
    if [ -e "$FE32_FOAM_ETC" ] && [ -d "$FE32_FOAM_ETC" ]; then

        # Clear old environment
        feClear

        # Restore basic environment variables
        [ ! -z "$FE32_FOAM_INST_DIR" ] && \
            env_set 'FOAM_INST_DIR' "$FE32_FOAM_INST_DIR"
        env_set 'FOAM_ETC' "$FE32_FOAM_ETC"
        env_set 'FOAM_USER_ETC' "$FE32_FOAM_USER_ETC"

        # Load new environment
        feLoad

    else

        local msg
            msg="Could not find 'bashrc' of foam-extend in folder"
            msg="$msg '$FOAM_ETC'. Did you either pass the path to the"
            msg="$msg foam-extend etc-directory as parameter \$1 to"
            msg="$msg this 'bashrc' or set FOAM_ETC directly instead?"
            msg="$msg Is foam-extend really installed, correctly?"

        error_fatal "$msg" 'fe32'

    fi
}

# --------------------------------------------------------------------------- #
# --------------------------------------------------------------------------- #
# --------------------------------------------------------------------------- #
