#!/bin/bash
# August 2015
# Pascal Beckstein (p.beckstein@hzdr.de)

# TODO [High] Sort this mess in cleanFunctions.sh and put it in case/.
# TODO [High] Sort this mess in helpFunctions.sh and put it in case/.

# --------------------------------------------------------------------------- #
# --- Sourcing -------------------------------------------------------------- #
# --------------------------------------------------------------------------- #

PSD="$(dirname "${BASH_SOURCE[0]}")";
sourcePSD () { local psd="$PSD"; source "$1"; PSD="$psd"; }

# --------------------------------------------------------------------------- #

sourcePSD "$PSD/bashrc.d/source.sh"

# --------------------------------------------------------------------------- #
# --- Function definitions -------------------------------------------------- #
# --------------------------------------------------------------------------- #

feClear ()
{
    # Backup keys
    local fe40_foam_inst_dir="$FE40_FOAM_INST_DIR"
    local fe40_foam_etc="$FE40_FOAM_ETC"
    local fe40_foam_user_etc="$FE40_FOAM_USER_ETC"

    # Clear environment
    env_unsetRegex WM_.*
    env_unsetRegex FOAM_.*
    env_removeAll 'foam'
    env_removeAll 'foam-extend'

    # Clear alias
    unalias pf &> /dev/null

    # Restore keys
    env_set 'FE40_FOAM_INST_DIR' "$fe40_foam_inst_dir"
    env_set 'FE40_FOAM_ETC' "$fe40_foam_etc"
    env_set 'FE40_FOAM_USER_ETC' "$fe40_foam_user_etc"
}


feLoad ()
{
    # Load project environment
    source "$FOAM_ETC/bashrc" &> /dev/null

    # Load user environment
    source "$FOAM_USER_ETC/user/source.sh"

    # Set alias
    alias pf='paraFoam -nativeReader &> /dev/null &'
}


fe40 ()
{
    if [ -e "$FE40_FOAM_ETC" ] && [ -d "$FE40_FOAM_ETC" ]; then

        # Clear old environment
        feClear

        # Restore basic environment variables
        [ ! -z "$FE40_FOAM_INST_DIR" ] && \
            env_set 'FOAM_INST_DIR' "$FE40_FOAM_INST_DIR"
        env_set 'FOAM_ETC' "$FE40_FOAM_ETC"
        env_set 'FOAM_USER_ETC' "$FE40_FOAM_USER_ETC"

        # Compile option (defaults to 'Opt')
        env_set 'WM_COMPILE_OPTION' "${1:-'Opt'}"

        # Load new environment
        feLoad

    else

        local msg
            msg="Could not find 'bashrc' of foam-extend in folder"
            msg="$msg '$FOAM_ETC'. Did you either pass the path to the"
            msg="$msg foam-extend etc-directory as parameter \$1 to"
            msg="$msg this 'bashrc' or set FOAM_ETC directly instead?"
            msg="$msg Is foam-extend really installed, correctly?"

        error_fatal "$msg" 'fe40'

    fi
}

# --------------------------------------------------------------------------- #
# --------------------------------------------------------------------------- #
# --------------------------------------------------------------------------- #
