#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake all freeSurface || exit 1
wmake all freeSurface.new || exit 1

wmake interTrackFoam || exit 1

wmake all trackedSurface || exit 1
wmake all trackedSurface.new || exit 1

wmake interTrackMHDFoam || exit 1
wmake interTrackMHDcoupledFoam || exit 1
wmake interTrackEddyCurrentFoam || exit 1
wmake interTrackEddyCurrentFoam.new || exit 1
