#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Cleanup
cleanCase
cleanFaMesh

# Fix bug in foam cleanFaMesh (using bash syntax with #!/bin/sh)
rm -rf constant/faMesh/faBoundary* 2>/dev/null
rm -rf constant/faMesh/faceLabels* 2>/dev/null

# Remove polyMesh boundary description
rm -rf constant/polyMesh/boundary 2>/dev/null
