#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanFaMesh ()
{
    rm -rf ./constant/faMesh/faceLabels* \
           ./constant/faMesh/faBoundary* \
           > /dev/null 2>&1
}

cleanHistoryFolder ()
{
    rm -rf ./history \
        > /dev/null 2>&1
}

cleanHistoryFolder
cleanTimeDirectories
cleanFaMesh

rm -rf processor*
rm -rf system/region0_faSubMesh;
rm -rf constant/region0_faSubMesh
