#!/bin/bash

# patchAverage 'c' 'trackedSurface' | grep 'Average of c over patch trackedSurface' | awk '{ print $8 }' > 'cmean.dat'
cat 'cmean.dat' | awk '!(NR%1)' > 'cmean.tmp'
foamUserToolFourierTransform 'cmean.tmp' '0.1'
