#!/bin/bash

patchAverage 'c' 'trackedSurface' | grep 'Average of c over patch trackedSurface' > 'cmean.tmp'
cat 'cmean.tmp' | awk '{ print $8 }' | awk 'NR%1==1' > 'cmean.dat'
foamUserToolFourierTransform 'cmean.dat' '0.1'